username: wenyuzhao
url: "https://wenyu.me"
baseurl: /
title: Wenyu Zhao
author: 赵文宇,Wenyu Zhao,wenyu.zhao@anu.edu.au,wenyuzhaox@gmail.com
common_keywords: 赵文宇,Wenyu Zhao,wenyuzhao,Memory Management,Garbage Collection,GC,MMTk,Software,Web,Server,iOS,Computer Science,Mathematics
default_description: freestyle
description_postfix: ' | Wenyu Zhao 赵文宇'
title_postfix: ' | Wenyu Zhao'

safe: false
highlighter: rouge
plugins:
  - jekyll-sitemap
