username: wenyuzhao
baseurl: 
title: Wenyu Zhao
author: 赵文宇,Wenyu Zhao,William,wenyuzhaox@gmail.com
common_keywords: 赵文宇,Wenyu Zhao,wenyuzhao,Software,Web,Server,iOS,Computer Science,Mathematics
default_description: freestyle
description_postfix: ' | Wenyu Zhao 赵文宇'
title_postfix: ' | Wenyu Zhao'

safe: false
highlighter: rouge
plugins:
  - jekyll-sitemap
