name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      # Caching
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
      # Setup
      - name: Setup
        uses: actions/setup-node@v2
      - name: Install
        run: |
          npm install -g yarn
          yarn install
      # Export static site
      - name: Build and export
        run: |
          yarn deploy
          touch out/.nojekyll
      # Deploy
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: out
